export const EMERGENCY_GUIDES = [
  {
    id: "earthquake",
    title: "Earthquake Response",
    description: "What to do during and after an earthquake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXmKBuS2qkINug0fgkO4SEKZdI-0Q1jbXTZQ&s",
    steps: [
      "DROP immediately to hands and knees",
      "Take COVER under a sturdy desk, table, or against an interior wall",
      "HOLD ON until shaking stops — protect your head and neck",
      "Stay in place for at least one minute after shaking stops",
      "Check for hazards like broken glass or structural damage",
      "Exit building only if it's safe — avoid elevators",
      "Go to designated assembly point or open area",
      "Report any injuries or trapped persons to emergency services",
    ],
  },
  {
    id: "flood",
    title: "Flood Emergency",
    description: "Essential steps to stay safe during flooding",
    image: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400",
    steps: [
      "Evacuate immediately to higher ground if flood warning issued",
      "Do NOT attempt to drive through flooded roads",
      "Move away from water sources and drainage areas",
      "Turn off gas and electricity if safe to do so",
      "Close windows and doors to slow water entry",
      "If trapped, move to highest point in building",
      "Signal for help from windows or roof",
      "Wait for rescue teams — do not attempt to swim",
    ],
  },
  {
    id: "typhoon",
    title: "Typhoon Preparation",
    description: "Prepare and stay safe during typhoons and hurricanes",
    image: "https://i0.wp.com/mandry.club/wp-content/uploads/2025/03/The-typhoon-can-be-seen-very-well.webp?ssl=1",
    steps: [
      "Monitor weather updates and emergency alerts",
      "Secure outdoor items that can become projectiles",
      "Stock emergency supplies: water, food, medication, flashlight",
      "Charge all electronic devices and backup power banks",
      "Fill bathtubs with water for emergency use",
      "Know your evacuation route and assembly point",
      "Stay indoors away from windows during storm",
      "Do NOT go outside during eye of typhoon — danger returns",
      "After storm, watch for hazards like downed power lines",
    ],
  },
  {
    id: "landslide",
    title: "Landslide Warning",
    description: "Recognize warning signs and respond to landslides",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaK_VgqtMxCnJjOn-YgQdtpcqhuVEqMO4Vaw&s",
    steps: [
      "Evacuate immediately if ordered by authorities",
      "Move away from slopes and hillsides",
      "Do NOT wait for official evacuation order if signs appear",
      "Look for warning signs: new cracks, tilting trees, unusual sounds",
      "Go to designated evacuation center or higher ground",
      "Take important documents and medications",
      "Avoid valleys and ravines where debris flows",
      "Do not return until authorities declare area safe",
    ],
  },
  {
    id: "fire",
    title: "Fire Emergency",
    description: "Critical steps to survive a fire emergency",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4yGkQFm3hQgxVHpegx7xe33ADAEWgledLSg&s",
    steps: [
      "Alert others — shout 'FIRE!' to notify people nearby",
      "Leave the building immediately using nearest exit or stairs",
      "Do NOT use elevators — they may trap you",
      "If smoke is present, crawl low to avoid smoke inhalation",
      "Feel doors before opening — if hot, find another route",
      "Close doors behind you to slow fire and smoke spread",
      "Meet at predetermined assembly point",
      "Call emergency services and provide location details",
    ],
  },
  {
    id: "severe-weather",
    title: "Severe Weather",
    description: "Stay safe during storms and lightning",
    image: "https://s.yimg.com/ny/api/res/1.2/tJCXvvSpVV6EEQPWQWSwbA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MTg7Y2Y9d2VicA--/https://media.zenfs.com/en/south_florida_sun_sentinel_national_820/e48a52192693f6a4d61928067517c2a6",
    steps: [
      "Go indoors or seek shelter in a substantial building",
      "Avoid contact with water and metal objects",
      "Stay away from windows and doors",
      "Unplug electrical appliances if safe to do so",
      "Do NOT use landline phones during lightning",
      "If caught outdoors, stay away from tall objects",
      "Crouch low with feet together if stuck outside",
      "Do NOT lie flat — get into crouching position",
      "Wait 30 minutes after last lightning before going outside",
    ],
  },
];

export const FIRST_AID_TOPICS = [
  {
    id: "cpr",
    title: "CPR",
    description: "Learn how to perform CPR and save a life",
    image: "https://cprcare.com/wp-content/uploads/2020/11/how-to-perform-cpr-on-adults-1024x684.jpg.webp",
    steps: [
      "Check responsiveness and call emergency services",
      "Place person on firm, flat surface",
      "Open airway by tilting head back slightly",
      "Give 30 chest compressions at least 2 inches deep",
      "Give 2 rescue breaths (if trained)",
      "Continue CPR until emergency personnel arrive or person revives",
      "If untrained, perform hands-only CPR (chest compressions only)",
      "Use an AED if available and follow voice prompts",
    ],
  },
  {
    id: "bleeding",
    title: "Severe Bleeding",
    description: "Stop bleeding and prevent blood loss",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcGHW-xumiWJeP9QAsNaZzZm5YJlBvWEk7LA&s",
    steps: [
      "Call emergency services immediately",
      "Wash hands if possible or use gloves",
      "Apply direct pressure with clean cloth or bandage",
      "Maintain pressure for 10-15 minutes without lifting",
      "If blood soaks through, add another cloth on top",
      "Elevate the wound above heart level if possible",
      "Apply pressure to artery if bleeding doesn't stop",
      "Monitor for signs of shock",
    ],
  },
  {
    id: "choking",
    title: "Choking",
    description: "Quick action to save someone from choking",
    image: "https://www.healthdigest.com/img/gallery/the-first-thing-you-should-do-if-you-see-somebody-choking/intro-1646328208.jpg",
    steps: [
      "Encourage coughing if person can breathe or cough",
      "Perform Heimlich maneuver: stand behind person",
      "Place fist just above navel, below ribcage",
      "Grasp fist with other hand",
      "Push upward and inward with quick, upward thrusts",
      "Repeat until object is dislodged",
      "If person becomes unconscious, start CPR",
      "Call emergency if unsuccessful",
    ],
  },
  {
    id: "fractures",
    title: "Fractures & Sprains",
    description: "Handle broken bones and sprains safely",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkdwvx4c9HslsTFpnSL7G8-ZnD0aj6M_1Qog&s",
    steps: [
      "Immobilize the injured area — do not move it",
      "Apply ice wrapped in cloth for 20 minutes",
      "Elevate the injured limb above heart level",
      "Use compression bandage if available",
      "Take over-the-counter pain relief if needed",
      "Avoid using injured area",
      "Seek medical attention for severe pain or deformity",
      "Watch for signs of compartment syndrome",
    ],
  },
  {
    id: "burns",
    title: "Burns",
    description: "Treat burns and prevent complications",
    image: "https://images.apollo247.in/pd-cms/cms/2025-12/First%20Aid%20for%20Burns%20Immediate%20Actions%20and%20Home%20Care.webp",
    steps: [
      "Cool the burn with cool (not cold) water for 10-20 minutes",
      "Remove tight jewelry and clothing from burned area",
      "Do NOT apply ice directly to the burn",
      "Cover burn with sterile, non-stick dressing",
      "Take pain relief medication if needed",
      "Do NOT pop blisters",
      "Seek medical attention for severe burns",
      "Watch for signs of infection",
    ],
  },
  {
    id: "shock",
    title: "Shock",
    description: "Recognize and manage shock effectively",
    image: "https://www.legalexpert.co.uk/wp-content/uploads/2021/03/electric-shock-claims.jpg",
    steps: [
      "Call emergency services immediately",
      "Lay person down with legs elevated 12 inches",
      "Keep person warm with blankets or coat",
      "Do NOT give food or water",
      "Reassure the person and keep them calm",
      "Monitor breathing and pulse continuously",
      "Be prepared to perform CPR if needed",
      "Treat any obvious injuries",
    ],
  },
];

export const CHECKLISTS = [
  {
    id: "home-kit",
    title: "Home Emergency Kit",
    color: "#EF4444",
    bgColor: "#FEF2F2",
    image: "https://www.mrcooper.com/blog/wp-content/uploads/2021/10/EmergencySurvivalKit_Blog.jpg",
    items: [
      "Water (1 gallon per person per day for 3+ days)",
      "Non-perishable food for 3+ days",
      "First aid kit with medications",
      "Flashlight and extra batteries",
      "Battery or hand-crank powered radio",
      "Medication and medical equipment",
      "Documents in waterproof container",
      "Cash and credit cards",
      "Whistle for signaling",
      "Dust mask or N95 respirator",
      "Plastic sheeting and duct tape",
      "Moist towelettes and garbage bags",
    ],
  },
  {
    id: "evacuation",
    title: "Evacuation Readiness",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    image: "https://media.istockphoto.com/id/1363765782/photo/parents-explaining-to-their-children-how-to-use-the-radio-in-an-emergency.jpg?s=612x612&w=0&k=20&c=sNNBbr1-9GB-dewIVcWwknNqt2liGVRAH1s4F8s2OKc=",
    items: [
      "Know your evacuation routes from home and work",
      "Practice evacuation drills with family",
      "Prepare bug-out bag with essentials",
      "Have car fueled to at least half-tank",
      "Know how to turn off utilities",
      "Have important documents in waterproof container",
      "Store copies of insurance policies and deeds",
      "Have pet carriers and supplies ready",
      "Plan meeting place for family members",
      "Establish out-of-area contact person",
      "Keep phone numbers written down",
      "Have sturdy shoes and clothing for each family member",
    ],
  },
  {
    id: "earthquake-prep",
    title: "Before Earthquake",
    color: "#3B82F6",
    bgColor: "#EFF6FF",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXmKBuS2qkINug0fgkO4SEKZdI-0Q1jbXTZQ&s",
    items: [
      "Secure heavy furniture to walls",
      "Store breakables in low cabinets",
      "Identify safe spots in each room",
      "Know where main electrical panel is",
      "Know where water shut-off valve is",
      "Know where gas shut-off valve is",
      "Have earthquake insurance if possible",
      "Teach children how to 'Drop, Cover, Hold On'",
      "Practice earthquake drills monthly",
      "Keep sturdy shoes near bed",
      "Have flashlights accessible in each room",
      "Store water and food supplies",
    ],
  },
  {
    id: "typhoon-prep",
    title: "Before Typhoon/Storm",
    color: "#8B5CF6",
    bgColor: "#F5F3FF",
    image: "https://i0.wp.com/mandry.club/wp-content/uploads/2025/03/The-typhoon-can-be-seen-very-well.webp?ssl=1",
    items: [
      "Monitor weather forecasts regularly",
      "Stock up on non-perishable food and water",
      "Charge all electronic devices",
      "Fill bathtub with water",
      "Secure outdoor furniture",
      "Trim tree branches near house",
      "Check roof and gutters for damage",
      "Test backup power sources",
      "Have emergency supplies easily accessible",
      "Know your evacuation route",
      "Fill prescriptions in advance",
      "Have cash on hand",
    ],
  },
  {
    id: "flood-prep",
    title: "Before Flood",
    color: "#06B6D4",
    bgColor: "#ECFEFF",
    image: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400",
    items: [
      "Know your flood risk zone",
      "Install backflow valve on sewer line",
      "Have sandbags or flood barriers ready",
      "Move valuables to higher levels",
      "Take photos of home and contents for insurance",
      "Have copies of insurance documents",
      "Know evacuation routes from your area",
      "Have emergency kit easily accessible",
      "Keep important documents waterproof",
      "Maintain emergency fund",
      "Identify high ground locations",
      "Store electrical equipment safely",
    ],
  },
  {
    id: "comms-plan",
    title: "Family Communication Plan",
    color: "#EC4899",
    bgColor: "#FDF2F8",
    image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=400",
    items: [
      "Establish out-of-state contact person",
      "Write down contact numbers for all family members",
      "Have list of phone numbers written down",
      "Plan meeting place outside your neighborhood",
      "Teach children how to call emergency services",
      "Have photos of family members in wallet",
      "Program phone numbers in phones",
      "Establish text-based communication protocol",
      "Plan for different communication methods",
      "Ensure children know address and phone number",
      "Have code word for emergency communication",
      "Update contact list regularly",
    ],
  },
];

export const EMERGENCY_CONTACTS = [
  {
    label: "Emergency Services",
    number: "911 or 112",
    color: "#dc2626",
    type: "call",
  },
  {
    label: "Disaster Response",
    number: "Local City/Municipality",
    color: "#991b1b",
    type: "call",
  },
  {
    label: "Medical Emergency",
    number: "Local Hospital / Ambulance",
    color: "#16a34a",
    type: "call",
  },
];

export const SUPPORT_SERVICES = [
  {
    title: "Medical Rescue",
    description: "Request emergency medical assistance",
    icon: "medical",
    color: "#dc2626",
  },
  {
    title: "Search & Rescue",
    description: "Request rescue for trapped individuals",
    icon: "rescue",
    color: "#ea580c",
  },
  {
    title: "Food & Water",
    description: "Request food and water supplies",
    icon: "food",
    color: "#ca8a04",
  },
  {
    title: "Emergency Shelter",
    description: "Request temporary shelter assistance",
    icon: "shelter",
    color: "#16a34a",
  },
];

export const KEY_REMINDERS = [
  "Know your evacuation route before an emergency occurs",
  "Have an emergency contact list and supplies ready",
  "Follow instructions from emergency personnel",
  "Stay informed through official emergency alerts",
];
