export const BARANGAY_OPTIONS = [
  { id: 1, label: "Aldavoc" },
  { id: 2, label: "Aliji" },
  { id: 3, label: "Bagong Silang" },
  { id: 4, label: "Bambán" },
  { id: 5, label: "Bosigon" },
  { id: 6, label: "Bukál" },
  { id: 7, label: "Cabibihan" },
  { id: 8, label: "Cabugwang" },
  { id: 9, label: "Cagascas" },
  { id: 10, label: "Candalapdap" },
  { id: 11, label: "Casispalan" },
  { id: 12, label: "Colong-colong" },
  { id: 13, label: "Del Rosario" },
  { id: 14, label: "Katimo" },
  { id: 15, label: "Kinatakutan" },
  { id: 16, label: "Landing" },
  { id: 17, label: "Laurel" },
  { id: 18, label: "Magsaysáy" },
  { id: 19, label: "Maguibuay" },
  { id: 20, label: "Mahinta" },
  { id: 21, label: "Malbog" },
  { id: 22, label: "Manato Central" },
  { id: 23, label: "Manato Station" },
  { id: 24, label: "Mangayao" },
  { id: 25, label: "Mansilay" },
  { id: 26, label: "Mapulot" },
  { id: 27, label: "Muntíng Parang" },
  { id: 28, label: "Payapà" },
  { id: 29, label: "Población" },
  { id: 30, label: "Rizal" },
  { id: 31, label: "Sabang" },
  { id: 32, label: "San Diego" },
  { id: 33, label: "San Francisco" },
  { id: 34, label: "San Isidro" },
  { id: 35, label: "San Roque" },
  { id: 36, label: "San Vicente" },
  { id: 37, label: "Santa Cecilia" },
  { id: 38, label: "Santa Monica" },
  { id: 39, label: "Santo Niño I" },
  { id: 40, label: "Santo Niño II" },
  { id: 41, label: "Santo Tomás" },
  { id: 42, label: "Seguiwan" },
  { id: 43, label: "Tabason" },
  { id: 44, label: "Tunton" },
  { id: 45, label: "Victoria" },
];

export const BARANGAY_NAMES = BARANGAY_OPTIONS.map((b) => b.label);
